/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "东腾的博客",
  "description": "",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/logo.png"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "进入我的博客",
        "actionLink": "/timeLine/",
        "subDescription": "一名爱技术、爱生活、爱思考的码农"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-10b0fe18",
      "path": "/"
    },
    {
      "frontmatter": {
        "home": false,
        "heroImage": "/img/banner.png",
        "heroText": "lhs的日常记录",
        "tagline": "喜欢打王者,只会射手",
        "features": [
          {
            "title": "是个160斤的胖子",
            "details": "是个160多斤的胖子,想要减肥,哪天你看不到这段话了,那说明我已经瘦下来了"
          }
        ]
      },
      "regularPath": "/home/home1.html",
      "relativePath": "home/home1.md",
      "key": "v-e3413950",
      "path": "/home/home1.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/timeLine/test.html",
      "relativePath": "timeLine/test.md",
      "key": "v-830e5420",
      "path": "/timeLine/test.html"
    }
  ],
  "themeConfig": {
    "logo": "/img/logo.png",
    "nav": [
      {
        "text": "首页",
        "link": "/home/"
      },
      {
        "text": "技术",
        "link": "/timeLine/"
      },
      {
        "text": "生活",
        "link": "/life/"
      },
      {
        "text": "思考",
        "link": "/ponder/"
      },
      {
        "text": "标签库",
        "link": "/tags/"
      },
      {
        "text": "关于",
        "link": "/about/"
      },
      {
        "text": "留言板",
        "link": "/massage/"
      },
      {
        "text": "链接",
        "items": [
          {
            "text": "简书",
            "link": "https://www.jianshu.com/u/cbc58f855e75"
          },
          {
            "text": "GitHub",
            "link": "https://github.com/zhuzhaohua"
          },
          {
            "text": "码云",
            "link": "https://gitee.com/kobuta"
          }
        ]
      }
    ],
    "lastUpdated": "Last Updated"
  }
}